### ISSUE TITLE
Thread Safe?

### ISSUE THREAD

**Issue by jonathanbruno** [pupi94/aliexpress-ruby-sdk#1]
My plan is to execute different requests for different aliexpress accounts.

```
AliexpressAPI::Base.activate_session 'my-token'
AliexpressAPI::DsOrder.create!( ... )
```

in another thread

```
AliexpressAPI::Base.activate_session 'my-second-token'
AliexpressAPI::DsOrder.create!( ... )
```

I can do this right ? I mean, that is what that `threadsafe_attribute` is for

```
include ThreadsafeAttributes
threadsafe_attribute :_session
```

**Comment by pupi94** [comment]
yup, the `_session` is a threadsafe attribute. We have tested and used in production environment

**Comment by pupi94** [comment]
> 我的计划是对不同的速卖通帐户执行不同的请求。
> 
> ```
> AliexpressAPI::Base.activate_session 'my-token'
> AliexpressAPI::DsOrder.create!( ... )
> ```
> 
> 在另一个线程中
> 
> ```
> AliexpressAPI::Base.activate_session 'my-second-token'
> AliexpressAPI::DsOrder.create!( ... )
> ```
> 
> 我可以这样做吗？我的意思是那`threadsafe_attribute`是为了
> 
> ```
> include ThreadsafeAttributes
> threadsafe_attribute :_session
> ```

yup, the _session is a threadsafe attribute. We have tested and used in production environment

**Comment by pupi94** [comment]
> My plan is to execute different requests for different aliexpress accounts.
> 
> ```
> AliexpressAPI::Base.activate_session 'my-token'
> AliexpressAPI::DsOrder.create!( ... )
> ```
> 
> in another thread
> 
> ```
> AliexpressAPI::Base.activate_session 'my-second-token'
> AliexpressAPI::DsOrder.create!( ... )
> ```
> 
> I can do this right ? I mean, that is what that `threadsafe_attribute` is for
> 
> ```
> include ThreadsafeAttributes
> threadsafe_attribute :_session
> ```

yup, the _session is a threadsafe attribute. We have tested and used in production environment
